### ISSUE TITLE
初始建议

### ISSUE THREAD

**Issue by Mq-b** [dynilath/modern-cpp-primer#1]
1. 我觉得需要先自定义 labels 标签，说明他们的作用。
2. 我觉得需要规范提交日志和记录，不应该全部随便都是 update xxx 这种玩意。
3. 我觉得你还应该打开讨论，目前这个项目没有讨论。
4. 我没有权限设置这个项目的链接，我觉得你应该设置好这个项目的阅读链接。
5. 你那个web，那玩意 moder-cpp-primer 少了个 `n`。
6. 还有他们的超链接，都是超链接到你用的那个框架的 github。

**Comment by dynilath** [comment]
1. 等至少初步完成一个章节再说
2. 那所有的日志都得是`[docs] xxxx`了，概述一下操作内容就行
3. 同1
4. 同1
5. 不太懂为啥你能在修正1小时后还能看到typo https://github.com/dynilath/modern-cpp-primer/commit/f15088bc6e46a79a8204c667af2dba42f331e41b
6. 不太懂为啥你能在修正1小时后还能看到设置错误 https://github.com/dynilath/modern-cpp-primer/commit/8f2c22c23f842576edf2027a659a65d172f5a3ed
