### ISSUE TITLE
标识符介绍中的矛盾

### ISSUE THREAD

**Issue by frederick-vs-ja** [dynilath/modern-cpp-primer#3]
https://github.com/dynilath/modern-cpp-primer/blob/d501e4d8d3063923c8d824ffd4f88b0deb207c1a/src/zh/01-hello-world/02-id-and-keyword.md?plain=1#L26-L29

但是 XID_Start/XID_Continue 的限制实际上禁用了几乎所有的 emoji。

**Comment by dynilath** [comment]
有道理，而且随手找了一下没找到 xids 和 xidc 的 emoji，我认为应该把这段描述里的 emoji 部分砍了

**Comment by dynilath** [comment]
在 b22b7aa 已解决
