### ISSUE TITLE
info 中使用 Markdown 的行内代码并不会渲染

### ISSUE THREAD

**Issue by Mq-b** [dynilath/modern-cpp-primer#4]
https://github.com/dynilath/modern-cpp-primer/blob/main/src/zh/02-program-structure/cli-program.md?plain=1#L223C1-L223C17

> :::info \`\{}\` 的作用

并不会渲染成：

> `{}` 的作用

**Comment by dynilath** [comment]
在 721257e8b03cb3ad678a2e9d28733ebcad787cf4 中已解决
